### ISSUE TITLE
如何去除自己数据的阴影？

### ISSUE THREAD

**Issue by smart4654154** [jinyeying/DeS3_Deshadow#4]
作者你好，现在我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，请问具体如何实现，谢谢

**Comment by jinyeying** [comment]
> 作者你好，现在我有一份无人机拍摄的数据，因为光线原因，有楼的阴影（无法提供无阴影的数据），我想去除，所以看到了这篇无监督去阴影的文章，请问具体如何实现，谢谢

啊, 这篇是有监督的去阴影的文章, 用的数据集是ISTD和SRD. self-shadow的去除主要是靠diffusion学到了clean data distribution.
